/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Code area minimap",
  "description": "Shows a zoomed-out overview of scripts. Click or drag in it to navigate the code area.",
  "tags": ["editor", "codeEditor"],
  "credits": [{"name": "griffpatch"}],
  "enabledByDefault": true,
  "dynamicDisable": true,
  "userscripts": [{"url": "userscript.js"}],
  "userstyles": [{"url": "userstyle.css"}],
  "settings": [{
    "dynamic": true,
    "name": "Minimap size",
    "id": "size",
    "type": "select",
    "potentialValues": [
      {"id": "small", "name": "Small"},
      {"id": "medium", "name": "Medium"},
      {"id": "large", "name": "Large"}
    ],
    "default": "small"
  }]
};
export default manifest;
